server:
  port: 8123
  servlet:
    context-path: /api
spring:
  redis:
    cluster:
      nodes: ${greendam.redis.cluster.nodes}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      driver-class-name: ${greendam.datasource.driver-class-name}
      url: jdbc:mysql://${greendam.datasource.host}:${greendam.datasource.port}/${greendam.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${greendam.datasource.username}
      password: ${greendam.datasource.password}
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: ${greendam.datasource.stat-view-servlet.login-username}
        login-password: ${greendam.datasource.stat-view-servlet.login-password}

  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
knife4j:
  enable: true
  openapi:
    title: 云相册接口文档
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.greendam.cloudphotoalbum.controller
greendam:
  alioss:
    endpoint: ${greendam.alioss.endpoint}
    bucket-name: ${greendam.alioss.bucket-name}
    access-key-id: ${greendam.alioss.access-key-id}
    access-key-secret: ${greendam.alioss.access-key-secret}

